version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - forcetypeassert
    - goconst
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
    - wsl_v5
  settings:
    importas:
      alias:
        - pkg: sigs.k8s.io/cluster-api/api/core/v1beta2
          alias: clusterv1
        - pkg: sigs.k8s.io/cluster-api/api/core/v1beta1
          alias: clusterv1beta1
    nlreturn:
      block-size: 2
    revive:
      confidence: 0
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - all
        - -ST1000
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: "sigs.k8s.io/cluster-api/api/core/v1beta1" is deprecated:'
      - linters:
          - staticcheck
        text: 'SA1019: "sigs.k8s.io/cluster-api/util/deprecated/v1beta1/conditions" is deprecated:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
