FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-openshift-4.20
WORKDIR /go/src/github.com/openshift/cluster-api-actuator-pkg
COPY . .
RUN make build && \
    mkdir -p /tmp/build && \
    cp /go/src/github.com/openshift/cluster-api-actuator-pkg/bin/cluster-api-actuator-pkg-tests-ext /tmp/build/cluster-api-actuator-pkg-tests-ext && \
    gzip /tmp/build/cluster-api-actuator-pkg-tests-ext

COPY --from=builder /tmp/build/cluster-api-actuator-pkg-tests-ext.gz .

LABEL io.k8s.display-name="OpenShift Cluster API Actuator Pkg Operator" \
    io.openshift.release.operator=true \
    io.openshift.tags="openshift,tests,e2e,e2e-extension"